name: flutter_gcaptcha_v3
description: A new Flutter package project.
version: 0.0.1
homepage: https://www.jitenbasnet.com.np

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter


  #dependency injection
  get_it: ^7.4.1
  injectable: ^2.1.1

  #state management
  flutter_bloc: ^8.1.2

  #data models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  #network requests
  dio: ^5.1.1

  #webview
  webview_flutter_plus: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  #functional programmings
  dartz: ^0.10.1

  #generators
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  freezed: ^2.3.3
  injectable_generator: ^2.1.4

  # route generator
  auto_route_generator: ^5.0.3

flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - assets/recaptcha/
     - assets/webpages/
